#Print verbose information or not
VERBOSE_MODE = False

#Information related to your messages
TENANT_INFO = {
	"name":"Yuanhao Zhu",
	"email_address":"",
	"phone_number":"",
	"message":""
}

#City names and values
CITY_NAMES = {
   "aargau":"Aargau",
   "aarau":"Aarau (Stadt)",
   "appenzell-innerrhoden":"Appenzell Innerrhoden",
   "appenzell-ausser":"Appenzell Ausser.",
   "baden":"Baden",
   "baselstadt":"Basel City",
   "baselland":"Basel Land",
   "bern":"Bern",
   "biel":"Biel",
   "brugg":"Brugg",
   "burgdorf":"Burgdorf",
   "chur":"Chur",
   "emmental":"Emmental",
   "frauenfeld":"Frauenfeld",
   "fribourg":"Fribourg",
   "frick":"Jura",
   "genf":"Geneva",
   "glarus":"Glarus",
   "graubunden":"Graubünden",
   "interlaken":"Interlaken",
   "jura":"Jura",
   "zurich-kloten":"Kloten (Zürich)",
   "langenthal":"Langenthal",
   "langnau":"Langnau",
   "laufenburg":"Laufenburg",
   "lausanne":"Lausanne",
   "loerrach":"Lörrach (DE)",
   "luzern":"Lucerne",
   "neuenburg":"Neuchâtel",
   "nidwalden":"Nidwalden",
   "obwalden":"Obwalden",
   "olten":"Olten",
   "ostschweiz":"Ostschweiz",
   "rapperswil-jona":"Rapperswil-Jona",
   "schaffhausen":"Schaffhausen",
   "solothurn":"Solothurn",
   "schwyz":"Schwyz",
   "spiez":"Spiez",
   "st-gallen":"St. Gallen",
   "saint-louis-fr":"Saint-Louis (FR)",
   "simmental-saanenland":"Simmental/Saanenland",
   "tessin":"Ticino",
   "thun":"Thun",
   "thurgau":"Thurgau",
   "uri":"Uri",
   "waadt":"Vaud",
   "waedenswil":"Wädenswil (ZHAW)",
   "wallis":"Wallis",
   "weil-am-rhein-de":"Weil am Rhein (DE)",
   "wil":"Wil",
   "winterthur":"Winterthur &amp; Agglomeration",
   "zug":"Zug",
   "zurich-stadt":"Zurich (City)",
   "zurich-altstetten":"Zürich (Altstetten, Höngg)",
   "zurich-oerlikon":"Zürich (Oerlikon, Seebach, Affoltern)",
   "zurich-lake":"Zürich (Rund um den See)",
   "zurich-aeugstertal":"Zürich (Aeugstertal, Affoltern am Albis)",
   "zurich":"Zurich (Unterland, Weinland, Limmattal)",
   "zurich-oberland":"Zürich (Oberland, Glattal)",
   "liechtenstein":"Liechtenstein",
}

